Attempt to fix missing `dotnet` test failure
We are seeing the following [error](https://github.com/pulumi/pulumi-azure/actions/runs/9408917782/job/25919253715?pr=2106):

```
X TestAccAppServiceCs (0s)
      program.go:1946: sample: /home/runner/work/pulumi-azure/pulumi-azure/examples/appservice-cs
      program.go:1951: pulumi: /usr/local/bin/pulumi
      program.go:852:
          	Error Trace:	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.118.0/testing/integration/program.go:852
          	            				/home/runner/work/pulumi-azure/pulumi-azure/examples/examples_dotnet_test.go:35
          	Error:      	Received unexpected error:
          	            	copying test to temp dir : Failed to prepare /tmp/p-it-fv-az566-2-appservice-0359b7cf-944562426: locating `dotnet` binary: Expected to find `dotnet` binary on $PATH: exec: "dotnet": executable file not found in $PATH
          	Test:       	TestAccAppServiceCs
```

I believe that was caused by https://github.com/pulumi/ci-mgmt/pull/943.